parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            -  '../src/Infrastructure/UI/'

    App\Infrastructure\UI\:
         resource: '../src/Infrastructure/UI/'
         tags: [ 'controller.service_arguments' ]

    _instanceof:
        App\Domain\Shared\Bus\Command\CommandHandler:
            tags: [ { name: messenger.message_handler, bus: command.bus } ]

        App\Domain\Shared\Bus\Query\QueryHandler:
            tags: [ { name: messenger.message_handler, bus: query.bus } ]

        App\Domain\Shared\Bus\Event\DomainEventSubscriber:
            tags: [ { name: messenger.message_handler, bus: event.bus } ]

    App\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
        arguments: ['@command.bus']

    App\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
        arguments: ['@query.bus']

    App\Infrastructure\Bus\Event\InMemorySymfonyEventBus:
        arguments: ['@event.bus']

