parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            -  '../src/Infrastructure/UI/'

    App\Infrastructure\UI\:
         resource: '../src/Infrastructure/UI/'
         tags: [ 'controller.service_arguments' ]

    _instanceof:
        # all services implementing the CommandHandlerInterface
        # will be registered on the command.bus bus
        App\Domain\Shared\Bus\Command\CommandHandler:
            tags: ['app.command_handler']

        # while those implementing QueryHandlerInterface will be
        # registered on the query.bus bus
        App\Domain\Shared\Bus\Query\QueryHandler:
            tags: ['app.query_handler']

    # Command/Query Handlers
    App\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
        arguments: [!tagged app.command_handler]

    App\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
        arguments: [!tagged app.query_handler]

    App\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
        arguments: [!tagged app.domain_event_subscriber]
