framework:
    messenger:
        # The bus that is going to be injected when injecting MessageBusInterface
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus:
                # the 'allow_no_handlers' middleware allows to have no handler
                # configured for this bus without throwing an exception
                default_middleware: allow_no_handlers
                middleware:
                    - validation
