swagger: "2.0"
info:
  description: "This is a sample server Symfony OS server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Symfony OS"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:250"
tags:
  - name: "zone"
    description: "Everything about your Zones"
    externalDocs:
      description: "Find out more"
      url: "http://localhost:250"

schemes:
  - "http"
paths:
  /zones:
    get:
      tags:
        - "zone"
      summary: "Get all zones"
      description: "Get all zones"
      operationId: "getAllZones"
      produces:
        - "application/json"

      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Zone"
        "400":
          description: "Invalid status value"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
  /zones/{zoneId}:
    get:
      tags:
        - "zone"
      summary: "Find zone by ID"
      description: "For valid response try integer IDs"
      operationId: "getZoneById"
      produces:
        - "application/json"
      parameters:
        - name: "zoneId"
          in: "path"
          description: "ID of zone that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Zone"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Zone not found"
  /lessons:
    get:
      tags:
        - "lessons"
      summary: "Get All Lessons"
      description: "Get all available lessons"
      operationId: "getAll"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Lesson"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Zone not found"

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Zone:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int"
      property_id:
        type: integer
        format: "int"
      name:
        type: "string"
        example: "First zone"
      tags:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/Tag"
    xml:
      name: "Zone"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"